### ISSUE TITLE
转存成功过上千条，运行中抛出这个异常，重启后问题依旧

### ISSUE THREAD

**Issue by vm8net** [hxz393/BaiduPanFilesTransfers#87]
运行出错，请重新运行本程序。错误信息如下：
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bpftUI.py", line 428, in main
  File "bpftUI.py", line 310, in handle_file_transfer
  File "bpftUI.py", line 325, in process_s_link
  File "retrying.py", line 49, in wrapped_f
  File "retrying.py", line 212, in call
  File "retrying.py", line 247, in get
  File "six.py", line 719, in reraise
  File "retrying.py", line 200, in call
  File "bpftUI.py", line 268, in transfer_files
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vm8net** [comment]
后面又好，估计是百度网盘提示什么信息，比如转存太多，要求验证码什么类，程序没接住。

**Comment by hxz393** [comment]
转存 1000 条以后会弹验证码，但输入验证码也会转存失败。之前更换公网 IP 地址可以解决，现在不清楚。

**Comment by san585666** [comment]
作者我终于找到你了 能添加你一下吗 Tiki2023

**Comment by san585666** [comment]
> 转存 1000 条以后会弹验证码，但输入验证码也会转存失败。之前更换公网 IP 地址可以解决，现在不清楚。

作者我等了一个月 每天都在看你是否回复 能添加一下吗 微Tiki2023

**Comment by hxz393** [comment]
#78

**Comment by san585666** [comment]
我这边找总归是有一个接口，可以调用 目前已经购买到软件 但是自己还没研究透逻辑
